public class InvestmentAdvisorFirmsWrapper {

	public class Item5E {
		public String Q5E1;
		public String Q5E2;
		public String Q5E3;
		public String Q5E4;
		public String Q5E5;
		public String Q5E6;
		public String Q5E7;
	}

	public class Part1A_X {
		public Item1_Y Item1;
		public MailingAddr Item2A;
		public Item2B Item2B;
		public Item3A_Z Item3A;
		public Item3B Item3B;
		public Item3C_Z Item3C;
		public MailingAddr Item5A;
		public MailingAddr Item5B;
		public MailingAddr Item5C;
		public MailingAddr Item5D;
		public MailingAddr Item5E;
		public MailingAddr Item5F;
		public MailingAddr Item5G;
		public MailingAddr Item5H;
		public MailingAddr Item5I;
		public MailingAddr Item5J;
		public MailingAddr Item5K;
		public MailingAddr Item5L;
		public Item6A Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public MailingAddr Item8A;
		public MailingAddr Item8B;
		public MailingAddr Item8C;
		public MailingAddr Item8D;
		public MailingAddr Item8E;
		public MailingAddr Item8F;
		public MailingAddr Item8G;
		public MailingAddr Item8H;
		public MailingAddr Item8I;
		public MailingAddr Item9A;
		public MailingAddr Item9B;
		public MailingAddr Item9C;
		public MailingAddr Item9D;
		public MailingAddr Item9E;
		public MailingAddr Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5D {		
		public Integer Q5DA1;
		public String Q5DA2;
		public Long Q5DA3;

		public Integer Q5DB1; 
		public String Q5DB2; 
		public Long Q5DB3; 

		public Integer Q5DC1; 
		public String Q5DC2; 
		public Long Q5DC3; 

		public Integer Q5DD1; 
		public Long Q5DD3; 

		public Integer Q5DE1;
		public Long Q5DE3;

		public Integer Q5DF1;
		public Long Q5DF3;

		public Integer Q5DG1;
		public String Q5DG2;
		public Long Q5DG3;

		public Integer Q5DH1;
		public String Q5DH2;
		public Long Q5DH3;

		public Integer Q5DI1;
		public String Q5DI2; 
		public Long Q5DI3; 

		public Integer Q5DJ1; 
		public String Q5DJ2; 
		public Long Q5DJ3; 

		public Integer Q5DK1; 
		public String Q5DK2;
		public Long Q5DK3; 

		public Integer Q5DL1; 
		public String Q5DL2; 
		public Long Q5DL3; 

		public Integer Q5DM1;
		public String Q5DM2; 
		public Long Q5DM3; 

		public Integer Q5DN1; 
		public String Q5DN2; 
		public Long Q5DN3;
	}

	public class Part1A_Y {
		public Item1_Z Item1;
		public MailingAddr Item2A;
		public Item2B Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public MailingAddr Item5A;
		public MailingAddr Item5B;
		public MailingAddr Item5C;
		public MailingAddr Item5D;
		public MailingAddr Item5E;
		public MailingAddr Item5F;
		public MailingAddr Item5G;
		public MailingAddr Item5H;
		public MailingAddr Item5I;
		public MailingAddr Item5J;
		public MailingAddr Item5K;
		public MailingAddr Item5L;
		public MailingAddr Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public MailingAddr Item8A;
		public MailingAddr Item8B;
		public MailingAddr Item8C;
		public MailingAddr Item8D;
		public MailingAddr Item8E;
		public MailingAddr Item8F;
		public MailingAddr Item8G;
		public MailingAddr Item8H;
		public MailingAddr Item8I;
		public MailingAddr Item9A;
		public MailingAddr Item9B;
		public MailingAddr Item9C;
		public MailingAddr Item9D;
		public MailingAddr Item9E;
		public MailingAddr Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5C {
		public String Q5C1;
		public Integer Q5C2;
	}

	public class Part1A_Z {
		public Item1_Z Item1;
		public MailingAddr Item2A;
		public Item2B Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C_Z Item3C;
		public MailingAddr Item5A;
		public MailingAddr Item5B;
		public MailingAddr Item5C;
		public MailingAddr Item5D;
		public MailingAddr Item5E;
		public MailingAddr Item5F;
		public MailingAddr Item5G;
		public MailingAddr Item5H;
		public MailingAddr Item5I;
		public MailingAddr Item5J;
		public MailingAddr Item5K;
		public MailingAddr Item5L;
		public MailingAddr Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public MailingAddr Item8A;
		public MailingAddr Item8B;
		public MailingAddr Item8C;
		public MailingAddr Item8D;
		public MailingAddr Item8E;
		public MailingAddr Item8F;
		public MailingAddr Item8G;
		public MailingAddr Item8H;
		public MailingAddr Item8I;
		public MailingAddr Item9A;
		public MailingAddr Item9B;
		public MailingAddr Item9C;
		public MailingAddr Item9D;
		public MailingAddr Item9E;
		public MailingAddr Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class NoticeFiled {
		public List<States> States;
	}

	public class Item5B {
		public Integer Q5B1;
		public Integer Q5B2;
		public Integer Q5B3;
		public Integer Q5B4;
		public Integer Q5B5;
		public Integer Q5B6;
	}

	public class Item5I {
		public String Q5I1;
		public Long Q5I2A;
		public Long Q5I2B;
		public Long Q5I2C;
	}

	public class Item3C_Z {
		public String CntryNm;
	}

	public class Item5F_Z {
		public String Q5F1;
		public Long Q5F2A;
		public Long Q5F2B;
		public Long Q5F2C;
		public Integer Q5F2D;
		public Integer Q5F2E;
		public Integer Q5F2F;
		public Integer Q5F3;
	}

	public class Part1A_T {
		public Item1_Z Item1;
		public Item2A Item2A;
		public MailingAddr Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public Item5A Item5A;
		public Item5B Item5B;
		public Item5C Item5C;
		public Item5D_W Item5D;
		public Item5E Item5E;
		public Item5F_Z Item5F;
		public Item5G Item5G;
		public Item5H_Z Item5H;
		public Item5I_Z Item5I;
		public Item5J Item5J;
		public Item5K Item5K;
		public Item5L Item5L;
		public MailingAddr Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public Item8A Item8A;
		public Item8B Item8B;
		public Item8C Item8C;
		public MailingAddr Item8D;
		public Item8E Item8E;
		public Item8F Item8F;
		public Item8G_Z Item8G;
		public Item8H Item8H;
		public Item8I Item8I;
		public Item9A_Z Item9A;
		public Item9B_Z Item9B;
		public Item9C Item9C;
		public Item9D Item9D;
		public MailingAddr Item9E;
		public Item9F Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5H {
		public String Q5H;
		public Integer Q5HMT500;
	}

	public class Part1A_U {
		public Item1_Z Item1;
		public Item2A Item2A;
		public MailingAddr Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public Item5A Item5A;
		public Item5B Item5B;
		public Item5C Item5C;
		public Item5D_X Item5D;
		public Item5E Item5E;
		public Item5F Item5F;
		public Item5G Item5G;
		public Item5H Item5H;
		public Item5I Item5I;
		public Item5J Item5J;
		public Item5K Item5K;
		public Item5L_Z Item5L;
		public Item6A Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public Item8A Item8A;
		public Item8B Item8B;
		public Item8C Item8C;
		public Item8D Item8D;
		public Item8E Item8E;
		public Item8F Item8F;
		public Item8G Item8G;
		public Item8H Item8H;
		public Item8I Item8I;
		public Item9A Item9A;
		public Item9B Item9B;
		public Item9C Item9C;
		public Item9D Item9D;
		public MailingAddr Item9E;
		public Item9F Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5G {
		public String Q5G1;
		public String Q5G2;
		public String Q5G3;
		public String Q5G4;
		public String Q5G5;
		public String Q5G6;
		public String Q5G7;
		public String Q5G8;
		public String Q5G9;
		public String Q5G10;
		public String Q5G11;
		public String Q5G12;
		public String Q5G12Oth;
	}

	public class Part1A_V {
		public Item1_Z Item1;
		public Item2A Item2A;
		public MailingAddr Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public Item5A Item5A;
		public Item5B Item5B;
		public Item5C Item5C;
		public Item5D_Y Item5D;
		public Item5E Item5E;
		public Item5F Item5F;
		public Item5G Item5G;
		public Item5H Item5H;
		public Item5I Item5I;
		public Item5J Item5J;
		public Item5K Item5K;
		public Item5L_Z Item5L;
		public MailingAddr Item6A;
		public Item6B Item6B;
		public MailingAddr Item7A;
		public Item7B Item7B;
		public Item8A Item8A;
		public Item8B Item8B;
		public Item8C Item8C;
		public MailingAddr Item8D;
		public Item8E Item8E;
		public Item8F Item8F;
		public Item8G_Z Item8G;
		public Item8H Item8H;
		public Item8I Item8I;
		public Item9A_Z Item9A;
		public Item9B_Z Item9B;
		public Item9C Item9C;
		public Item9D Item9D;
		public MailingAddr Item9E;
		public Item9F Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5F {
		public String Q5F1;
		public Long Q5F2A;
		public Long Q5F2B;
		public Long Q5F2C;
		public Integer Q5F2D;
		public Integer Q5F2E;
		public Integer Q5F2F;
		public Long Q5F3;
	}

	public class Part1A_W {
		public Item1 Item1;
		public Item2A Item2A;
		public MailingAddr Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public Item5A Item5A;
		public Item5B Item5B;
		public Item5C Item5C;
		public Item5D_Z Item5D;
		public Item5E Item5E;
		public Item5F Item5F;
		public Item5G Item5G;
		public MailingAddr Item5H;
		public Item5I Item5I;
		public Item5J Item5J;
		public Item5K Item5K;
		public Item5L_Z Item5L;
		public Item6A Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public Item8A Item8A;
		public Item8B Item8B;
		public Item8C Item8C;
		public Item8D Item8D;
		public Item8E Item8E;
		public MailingAddr Item8F;
		public Item8G Item8G;
		public Item8H Item8H;
		public Item8I Item8I;
		public Item9A Item9A;
		public Item9B Item9B;
		public Item9C Item9C;
		public Item9D Item9D;
		public MailingAddr Item9E;
		public Item9F Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5L {
		public String Q5L1A;
		public String Q5L1B;
		public String Q5L1C;
		public String Q5L1D;
		public String Q5L1E;
		public String Q5L2;
		public String Q5L3;
		public String Q5L4;
	}

	public class Item5K {
		public String Q5K1;
		public String Q5K2;
		public String Q5K3;
		public String Q5K4;
	}

	public class Part1A_R {
		public Item1_X Item1;
		public MailingAddr Item2A;
		public Item2B Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C_Z Item3C;
		public MailingAddr Item5A;
		public MailingAddr Item5B;
		public MailingAddr Item5C;
		public MailingAddr Item5D;
		public MailingAddr Item5E;
		public MailingAddr Item5F;
		public MailingAddr Item5G;
		public MailingAddr Item5H;
		public MailingAddr Item5I;
		public MailingAddr Item5J;
		public MailingAddr Item5K;
		public MailingAddr Item5L;
		public Item6A Item6A;
		public Item6B_Z Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public MailingAddr Item8A;
		public MailingAddr Item8B;
		public MailingAddr Item8C;
		public MailingAddr Item8D;
		public MailingAddr Item8E;
		public MailingAddr Item8F;
		public MailingAddr Item8G;
		public MailingAddr Item8H;
		public MailingAddr Item8I;
		public MailingAddr Item9A;
		public MailingAddr Item9B;
		public MailingAddr Item9C;
		public MailingAddr Item9D;
		public MailingAddr Item9E;
		public MailingAddr Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Item5J {
		public String Q5J1;
		public String Q5J2;
	}

	public class Part1A_S {
		public Item1 Item1;
		public MailingAddr Item2A;
		public Item2B Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C_Z Item3C;
		public MailingAddr Item5A;
		public MailingAddr Item5B;
		public MailingAddr Item5C;
		public MailingAddr Item5D;
		public MailingAddr Item5E;
		public MailingAddr Item5F;
		public MailingAddr Item5G;
		public MailingAddr Item5H;
		public MailingAddr Item5I;
		public MailingAddr Item5J;
		public MailingAddr Item5K;
		public MailingAddr Item5L;
		public Item6A Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public MailingAddr Item8A;
		public MailingAddr Item8B;
		public MailingAddr Item8C;
		public MailingAddr Item8D;
		public MailingAddr Item8E;
		public MailingAddr Item8F;
		public MailingAddr Item8G;
		public MailingAddr Item8H;
		public MailingAddr Item8I;
		public MailingAddr Item9A;
		public MailingAddr Item9B;
		public MailingAddr Item9C;
		public MailingAddr Item9D;
		public MailingAddr Item9E;
		public MailingAddr Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class Rgstn {
		public String FirmType;
		public String St;
		public String Dt;
	}

	public class States {
		public String RgltrCd;
		public String St;
		public String Dt;
	}

	public class Item6B {
		public String Q6B1;
		public String Q6B3;
	}

	public class Item6A {
		public String Q6A1;
		public String Q6A2;
		public String Q6A3;
		public String Q6A4;
		public String Q6A5;
		public String Q6A6;
		public String Q6A7;
		public String Q6A8;
		public String Q6A9;
		public String Q6A10;
		public String Q6A11;
		public String Q6A12;
		public String Q6A13;
		public String Q6A14;
	}

	public class Item8G_Z {
		public String Q8G1;
	}

	public class MainAddr_V {
		public String Strt1;
		public String City;
		public String Cntry;
		public String PostlCd;
		public String PhNb;
		public String FaxNb;
	}

	public class MainAddr_X {
		public String Strt1;
		public String City;
		public String State;
		public String Cntry;
		public String PostlCd;
		public String PhNb;
	}

	public class MainAddr_W {
		public String Strt1;
		public String Strt2;
		public String City;
		public String Cntry;
		public String PostlCd;
		public String PhNb;
	}

	public class MainAddr_Z {
		public String Strt1;
		public String Strt2;
		public String City;
		public String Cntry;
		public String PhNb;
		public String FaxNb;
	}

	public class MainAddr_Y {
		public String Strt1;
		public String City;
		public String State;
		public String Cntry;
		public String PostlCd;
		public String PhNb;
		public String FaxNb;
	}

	public class Filing {
		public String Dt;
		public String FormVrsn;
	}

	public class MainAddr {
		public String Strt1;
		public String Strt2;
		public String City;
		public String State;
		public String Cntry;
		public String PostlCd;
		public String PhNb;
		public String FaxNb;
	}

	public class Item5A {
		public Integer TtlEmp;
	}

	public Total total;
	public List<Filings> filings;

	public class Item11E {
		public String Q11E1;
		public String Q11E2;
		public String Q11E3;
		public String Q11E4;
	}

	public class Item11F {
		public String Q11F;
	}

	public class Item11C {
		public String Q11C1;
		public String Q11C2;
		public String Q11C3;
		public String Q11C4;
		public String Q11C5;
	}

	public class Item11D {
		public String Q11D1;
		public String Q11D2;
		public String Q11D3;
		public String Q11D4;
		public String Q11D5;
	}

	public class Item9A_Z {
		public String Q9A1A;
		public String Q9A1B;
	}

	public class Item11G {
		public String Q11G;
	}

	public class Item11H {
		public String Q11H1A;
		public String Q11H1B;
		public String Q11H1C;
		public String Q11H2;
	}

	public class Item11A {
		public String Q11A1;
		public String Q11A2;
	}

	public class Item11B {
		public String Q11B1;
		public String Q11B2;
	}

	public class Item8D {
		public String Q8D;
	}

	public class Item8C {
		public String Q8C1;
		public String Q8C2;
		public String Q8C3;
		public String Q8C4;
	}

	public class Item8B {
		public String Q8B1;
		public String Q8B2;
		public String Q8B3;
	}

	public class Item8A {
		public String Q8A1;
		public String Q8A2;
		public String Q8A3;
	}

	public class Item1 {
		public WebAddrs WebAddrs;
		public Integer Q1F5;
		public String Q1I;
		public String Q1M;
		public String Q1N;
		public String Q1O;
		public String Q1P;
	}

	public class Item5H_Z {
		public String Q5H;
		public Integer Q5HMT500;
	}

	public class Item7B {
		public String Q7B;
	}

	public class Item7A {
		public String Q7A1;
		public String Q7A2;
		public String Q7A3;
		public String Q7A4;
		public String Q7A5;
		public String Q7A6;
		public String Q7A7;
		public String Q7A8;
		public String Q7A9;
		public String Q7A10;
		public String Q7A11;
		public String Q7A12;
		public String Q7A13;
		public String Q7A14;
		public String Q7A15;
		public String Q7A16;
	}

	public class Filings {
		public Info Info;
		public MainAddr MainAddr;
		public MailingAddr MailingAddr;
		public List<Rgstn> Rgstn;
		public MailingAddr NoticeFiled;
		public List<Filing> Filing;
		public FormInfo FormInfo;
		public Integer id;
	}

	public class Item5L_Z {
		public String Q5L1A;
		public String Q5L1B;
		public String Q5L1C;
		public String Q5L1D;
		public String Q5L1E;
		public String Q5L3;
		public String Q5L4;
	}

	public class Item5D_X {
		public Integer Q5DF1;
		public Integer Q5DF3;
		public Integer Q5DN1;
		public String Q5DN2;
		public Integer Q5DN3;
		public String Q5DN3Oth;
	}

	public class Item5D_W {
		public Integer Q5DA1;
		public Integer Q5DA3;
		public Integer Q5DB1;
		public Integer Q5DB3;
		public Integer Q5DG1;
		public Long Q5DG3;
	}

	public class Item9F {
		public Integer Q9F;
	}

	public class Item9E {
		public String Q9E;
	}

	public class Item3A_Z {
		public String OrgFormNm;
		public String OrgFormOthNm;
	}

	public class Item5D_Z {
		public Integer Q5DF1;
		public Integer Q5DF3;
		public Integer Q5DG1;
		public Integer Q5DG3;
		public String Q5DH2;
		public Integer Q5DH3;
		public String Q5DN2;
		public Integer Q5DN3;
		public String Q5DN3Oth;
	}

	public class Item5D_Y {
		public Integer Q5DA1;
		public Integer Q5DA3;
		public Integer Q5DB1;
		public Integer Q5DB3;
	}

	public class Item9B_Z {
		public String Q9B1A;
		public String Q9B1B;
	}

	public class Part1A {
		public Item1 Item1;
		public Item2A Item2A;
		public MailingAddr Item2B;
		public Item3A Item3A;
		public Item3B Item3B;
		public Item3C Item3C;
		public Item5A Item5A;
		public Item5B Item5B;
		public Item5C Item5C;
		public Item5D Item5D;
		public Item5E Item5E;
		public Item5F Item5F;
		public Item5G Item5G;
		public Item5H Item5H;
		public Item5I Item5I;
		public Item5J Item5J;
		public Item5K Item5K;
		public Item5L Item5L;
		public MailingAddr Item6A;
		public Item6B Item6B;
		public Item7A Item7A;
		public Item7B Item7B;
		public Item8A Item8A;
		public Item8B Item8B;
		public Item8C Item8C;
		public Item8D Item8D;
		public Item8E Item8E;
		public Item8F Item8F;
		public Item8G Item8G;
		public Item8H Item8H;
		public Item8I Item8I;
		public Item9A Item9A;
		public Item9B Item9B;
		public Item9C Item9C;
		public Item9D Item9D;
		public Item9E Item9E;
		public Item9F Item9F;
		public Item10A Item10A;
		public Item11 Item11;
		public Item11A Item11A;
		public Item11B Item11B;
		public Item11C Item11C;
		public Item11D Item11D;
		public Item11E Item11E;
		public Item11F Item11F;
		public Item11G Item11G;
		public Item11H Item11H;
	}

	public class WebAddrs {
		public String WebAddr;
	}

	public class Item8H {
		public String Q8H1;
		public String Q8H2;
	}

	public class Item8G {
		public String Q8G1;
		public String Q8G2;
	}

	public class Item6B_Z {
		public String Q6B1;
		public String Q6B2;
		public String Q6B3;
	}

	public class Item8F {
		public String Q8F;
	}

	public class Item8E {
		public String Q8E;
	}

	public class FormInfo {
		public Part1A Part1A;
	}

	public class MailingAddr {
	}

	public class Item8I {
		public String Q8I;
	}

	public class Item11 {
		public String Q11;
	}

	public class Item10A {
		public String Q10A;
	}

	public class Item9A {
		public String Q9A1A;
		public String Q9A1B;
		public Long Q9A2A;
		public Long Q9A2B;
	}

	public class Item5I_Z {
		public String Q5I1;
		public Integer Q5I2A;
		public Integer Q5I2B;
		public Integer Q5I2C;
	}

	public class Item9D {
		public String Q9D1;
		public String Q9D2;
	}

	public class Item9C {
		public String Q9C1;
		public String Q9C2;
		public String Q9C3;
		public String Q9C4;
	}

	public class Item9B {
		public String Q9B1A;
		public String Q9B1B;
		public Long Q9B2A;
		public Long Q9B2B;
	}

	public class Item3C {
		public String StateCD;
		public String CntryNm;
	}

	public class Item3B {
		public String Q3B;
	}

	public class Item3A {
		public String OrgFormNm;
	}

	public class FormInfo_Y {
		public Part1A_Y Part1A;
	}

	public class FormInfo_Z {
		public Part1A_Z Part1A;
	}

	public class FormInfo_W {
		public Part1A_W Part1A;
	}

	public class FormInfo_X {
		public Part1A_X Part1A;
	}

	public class FormInfo_U {
		public Part1A_U Part1A;
	}

	public class FormInfo_V {
		public Part1A_V Part1A;
	}

	public class FormInfo_S {
		public Part1A_S Part1A;
	}

	public class FormInfo_T {
		public Part1A_T Part1A;
	}

	public class FormInfo_R {
		public Part1A_R Part1A;
	}

	public class Item2B {
		public String Q2B1;
		public String Q2B2;
		public String Q2B3;
	}

	public class Item2A {
		public String Q2A1;
		public String Q2A2;
		public String Q2A4;
		public String Q2A5;
		public String Q2A6;
		public String Q2A7;
		public String Q2A8;
		public String Q2A9;
		public String Q2A10;
		public String Q2A11;
		public String Q2A12;
		public String Q2A13;
	}

	public class Item1_Y {
		public MailingAddr WebAddrs;
		public Long Q1F5;
		public String Q1I;
		public String Q1M;
		public String Q1N;
		public String Q1O;
		public String Q1P;
	}

	public class Item1_Z {
		public WebAddrs WebAddrs;
		public Long Q1F5;
		public String Q1I;
		public String Q1M;
		public String Q1N;
		public String Q1O;
	}

	public class Info_Z {
		public String SECRgnCD;
		public Integer FirmCrdNb;
		public String SECNb;
		public String BusNm;
		public String LegalNm;
	}

	public class Info {
		public String SECRgnCD;
		public Integer FirmCrdNb;
		public String SECNb;
		public String BusNm;
		public String LegalNm;
		public String UmbrRgstn;
	}

	public class Item1_X {
		public WebAddrs WebAddrs;
		public Integer Q1F5;
		public String Q1I;
		public String Q1M;
		public String Q1N;
		public String Q1O;
		public String Q1ODesc;
		public String Q1P;
	}

	public class Total {
		public Integer value;
		public String relation;
	}

	
	public static InvestmentAdvisorFirmsWrapper parse(String json) {
		return (InvestmentAdvisorFirmsWrapper) System.JSON.deserialize(json, InvestmentAdvisorFirmsWrapper.class);
	}
}